import $ from 'jquery'
import 'slick-carousel'
import mixitup from 'mixitup'
import { Fancybox } from '../../node_modules/@fancyapps/ui/dist/fancybox/fancybox.esm.js'

window.jQuery = window.$ = $

import * as flsFunctions from './modules/functions.js'

flsFunctions.isWebp()

import Swiper, { Autoplay, Navigation, Pagination } from 'swiper'

const swiper = new Swiper()

//translate

var arrLang = {
	en: {
		//promo
		collection: 'Collection',
		gallery: 'Gallery',
		diploma: 'Diploma',
		title: 'Portraits of Belarusian Universities',
		subtitle: 'NFT Collection',
		marquee: '// BSUCA // BSMU // BNTU // BSEU // BSUIR // BSU',
		//gallery
		gallery_title: 'Gallery',
		bguki_title: 'BSUCA',
		bguki_date: 'Date of foundation: 1975',
		more_btn: 'About it',
		bgu_title: 'BSU',
		bgu_date: 'Date of foundation: 1925',
		bgmu_title: 'BSMU',
		bgmu_date: 'Date of foundation: 1925',
		bntu_title: 'BNTU',
		bntu_date: 'Date of foundation: 1920',
		bgeu_title: 'BSEU',
		bgeu_date: 'Date of foundation: 1933',
		bguir_title: 'BSUIR',
		bguir_date: 'Date of foundation: 1964',
		gallery_info:
			"Artificial intelligence generated portraits reflecting the character and atmosphere of the country's leading universities.",
		//roadmap
		roadmap_title: 'Roadmap',
		roadmap_1: 'Setting goals, developing goals. Creation of prototypes and study of technologies.',
		roadmap_2: 'Writing the theoretical part of the thesis and developing the layout of the NFT collection site.',
		roadmap_3: 'Generation of images using a neural network, website development.',
		roadmap_4:
			'Adding images to the blockchain, completing the development of the site and finalizing the practical part of the thesis.',
		roadmap_5: 'Thesis defense, demonstration of the collection.',
		roadmap_progress_5: 'Performed',
		roadmap_progress: 'Done',
		//faq
		faq_title: 'FAQ',
		faq_que_1: 'How it works?',
		faq_text_1:
			'NFT, or Non-Fungible Token, is a unit of account by which a digital impression is created for any unique item. Among them can be: paintings, photographs, videos, music, gifs - in a word, any content that claims to be at least some kind of uniqueness. They are highly prized among collectors, gamers and art lovers, and are bought and sold through auctions.',
		faq_que_2: 'What quantity?',
		faq_text_2:
			'Portraits of Belarusian universities were issued in the amount of six pieces. The NFT of each portrait will be created in a single copy.',
		faq_que_3: 'How is it done?',
		faq_text_3:
			'NFTs were created on the basis of the Polygon blockchain using the OpenSea marketplace, detailed instructions for creating are described in the practical part of the thesis.',
		faq_que_4: 'Artificial intelligence - author?',
		faq_text_4:
			'According to the copyright law of the Republic of Belarus, the copyright for the images generated by the neural network belongs to the author of the keywords chosen to create the image. Since these words are the product of human creative activity.',
		faq_que_5: 'For whom?',
		faq_text_5:
			'Anyone can buy one of the six or all the portraits of Belarusian universities at once. These are one-of-a-kind illustrations created by artificial intelligence.',
		faq_que_6: 'Practical significance?',
		faq_text_6:
			'The collection is designed to showcase the application of NFT technology to the arts. A thesis, a collection, an image site are a ready-made and complete example of the application of technology in the field of art.',
		faq_que_7: 'How to get NFT?',
		faq_text_7: 'Tokens can be purchased from the non-fungible token marketplace - OpenSea.',
		//diploma
		diploma_title: 'Diploma',
		diploma_text:
			'The diploma project was developed by a student of the 408 group Kachura Yaroslav. The object of the thesis is NFT technology. The subject of the thesis is NFT technology in a digital art design project. The purpose of the thesis is the theoretical substantiation of a design project based on NFT technology in the field of digital art. The entire collection is designed by MidJourney artificial intelligence and hosted on the Polygon blockchain. ',
		info_1: 'HIGHER EDUCATION INSTITUTIONS',
		info_2: 'DIPLOMA PAGES',
		info_3: 'YEARS OF TRAINING',
		info_4: 'LINES OF CODE',
		info_5: 'EXPERIENCE',
		//footer
		footer_text: 'Дыпломны праект «Партрэты ўніверсітэтаў Беларусі»'
	},
	by: {
		//promo
		collection: 'Калекцыя',
		gallery: 'Галерыя',
		diploma: 'Дыплом',
		title: 'Партрэты Беларускіх Універсітэтаў',
		subtitle: 'Калекцыя NFT',
		marquee: '// БДУКІ // БДМУ // БНТУ // БДЭУ // БДУІР // БДУ',
		//gallery
		gallery_title: 'Галерэя',
		bguki_title: 'БДУКІ',
		bguki_date: 'Дата заснавання: 1975',
		more_btn: 'Падрабязней',
		bgu_title: 'БДУ',
		bgu_date: 'Дата заснавання: 1925',
		bgmu_title: 'БДМУ',
		bgmu_date: 'Дата заснавання: 1925',
		bntu_title: 'БНТУ',
		bntu_date: 'Дата заснавання: 1920',
		bgeu_title: 'БДЭУ',
		bgeu_date: 'Дата заснавання: 1933',
		bguir_title: 'БДУІР',
		bguir_date: 'Дата заснавання: 1964',
		gallery_info: 'Штучны інтэлект згенераваў партрэты, якія адлюстроўваюць характар ​​і атмасферу вядучых ВНУ краіны.',
		//roadmap
		roadmap_title: 'Стадыі',
		roadmap_1: 'Пастаноўка задач, распрацоўка мэт. Стварэнне прататыпаў і вывучэнне тэхналогій.',
		roadmap_2: 'Напісанне тэарэтычнай часткі дыплома і распрацоўка макета сайта NFT-калекцыі.',
		roadmap_3: 'Генерацыя малюнкаў пры дапамозе нейрасеткі, распрацоўка сайта.',
		roadmap_4:
			'Даданне малюнкаў у блокчэйн, заканчэнне распрацоўкі сайта і дапрацоўка практычнай часткі дыпломнай працы.',
		roadmap_5: 'Абарона дыпломнай працы, дэманстрацыя калекцыі.',
		roadmap_progress_5: 'Выконваецца',
		roadmap_progress: 'Выканана',
		//faq
		faq_title: 'Папулярныя пытанні',
		faq_que_1: 'Як гэта працуе?',
		faq_text_1:
			"NFT, або невзаезаменны токен, - гэта адзінка ўліку, з дапамогай якой ствараецца лічбавы злепак для любога унікальнага прадмета. Сярод іх могуць быць: карціны, фатаграфіі, відэа, музыка, гіфкі - словам, любы кантэнт, які прэтэндуе на хоць нейкую ўнікальнасць. Яны з'яўляюцца вялікай каштоўнасцю сярод калекцыянераў, геймераў і аматараў мастацтва, а купляюць і прадаюць іх праз аўкцыёны.",
		faq_que_2: 'Якая колькасць?',
		faq_text_2:
			'Партрэты беларускіх ВНУ выпушчаны ў колькасці шасці штук. NFT кожнага партрэта будзе створана ў адзіным экзэмпляры.',
		faq_que_3: 'Як гэта зроблена?',
		faq_text_3:
			'NFT былі створаны на базе блокчейна Polygon пры дапамозе маркетплэйса OpenSea, падрабязная інструкцыя стварэння апісана ў практычнай частцы дыпломнай працы.',
		faq_que_4: 'Штучны інтэлек - аўтар?',
		faq_text_4:
			"Згодна з законам аб аўтарскім праве Рэспублікі Беларусь, аўтарскае права на згенераваныя нейрасецю выявы належыць аўтару ключавых слоў, падабраных для стварэння выявы. Бо дадзеныя словы з'яўляюцца прадуктам творчай дзейнасці чалавека.",
		faq_que_5: 'Для каго?',
		faq_text_5:
			'Любы жадаючы можа набыць адзін з шасці ці адразу ўсе партрэты ўніверсітэтаў Беларусі. Гэта ўнікальныя ў сваім родзе ілюстрацыі, створаныя штучным інтэлектам.',
		faq_que_6: 'Практычнае значэнне?',
		faq_text_6:
			"Калекцыя распрацавана з мэтай дэманстрацыі прымянення ў сферы мастацтва тэхналогіі NFT. Дыпломная праца, калекцыя, іміджавы сайт з'яўляюцца гатовым і скончаным прыкладам ужывання тэхналогіі ў сферы мастацтва.",
		faq_que_7: 'Як атрымаць NFT?',
		faq_text_7: 'Токены можна набыць на гандлёвай пляцоўку для незамяняльных токенаў – OpenSea.',
		//diploma
		diploma_title: 'Дыплом',
		diploma_text:
			"Дыпломны праект распрацаваў студэнт 408 групы Качура Яраслаў. Аб'ектам дыпломнай працы з'яўляецца тэхналогія NFT. Прадметам дыпломнай працы з'яўляецца тэхналогія NFT у дызайн-праекце лічбавага мастацтва. Мэта дыпломнай працы - тэарэтычнае абгрунтаванне дызайн-праекта на аснове тэхналогіі NFT у сферы лічбавага мастацтва. Уся калекцыя распрацавана штучным інтэлектам MidJourney і размешчана на блокчейне Polygon. ",
		info_1: 'ВНУ',
		info_2: 'СТАРОНАК ДЫПЛОМА',
		info_3: 'ГАДЫ НАВУЧАННЯ',
		info_4: 'РАДОК КОДА',
		info_5: 'ДОСВЕД',
		//footer
		footer_text: 'Дыпломны праект «Партрэты ўніверсітэтаў Беларусі»'
	},
	ru: {
		//promo
		collection: 'Коллекция',
		gallery: 'Галерия',
		diploma: 'Диплом',
		title: 'Портреты Белорусских Университетов',
		subtitle: 'Коллекция NFT',
		marquee: '// БГУКИ // БГМУ // БНТУ // БГЭУ // БГУИР // БГУ',
		//gallery
		gallery_title: 'Галерея',
		bguki_title: 'БГУКИ',
		bguki_date: 'Дата основания: 1975',
		more_btn: 'Подробнее',
		bgu_title: 'БГУ',
		bgu_date: 'Дата основания: 1925',
		bgmu_title: 'БГМУ',
		bgmu_date: 'Дата основания: 1925',
		bntu_title: 'БНТУ',
		bntu_date: 'Дата основания: 1920',
		bgeu_title: 'БГЭУ',
		bgeu_date: 'Дата основания: 1933',
		bguir_title: 'БГУИР',
		bguir_date: 'Дата основания: 1964',
		gallery_info: 'Искусственный интеллект сгенерировал портреты отражающие характер и атмосферу ведущих ВУЗов страны.',
		//roadmap
		roadmap_title: 'Стадии',
		roadmap_1: 'Постановка задач, разработка целей. Создание прототипов и изучение технологий.',
		roadmap_2: 'Написание теоретической части диплома и разработка макета сайта NFT-коллекции.',
		roadmap_3: 'Генерация изображений при помощи нейросети, разработка сайта.',
		roadmap_4:
			'Добавление изображений в блокчейн, окончание разработки сайта и доработка практической части дипломной работы.',
		roadmap_5: 'Защита дипломной работы, демонстрация коллекции.',
		roadmap_progress_5: 'Выполняется',
		roadmap_progress: 'Выполнено',
		//faq
		faq_title: 'Часто задаваемые вопросы',
		faq_que_1: 'Как это работает?',
		faq_text_1:
			'NFT, или невзаимозаменяемый токен, — это единица учета, с помощью которой создается цифровой слепок для любого уникального предмета. Среди них могут быть: картины, фотографии, видео, музыка, гифки — словом, любой контент, претендующий на хоть какую-то уникальность. Они являются большой ценностью среди коллекционеров, геймеров и любителей искусства, а покупают и продают их через аукционы.',
		faq_que_2: 'Какое количество?',
		faq_text_2:
			'Портреты белорусских вузов выпущены в количестве шести штук. NFT каждого портрета будет создано в единственном экземпляре.',
		faq_que_3: 'Как это сделано?',
		faq_text_3:
			'NFT были созданы на базе блокчейна Polygon при помощи маркетплейса OpenSea, подробная инструкция создания описана в практической части дипломной работы.',
		faq_que_4: 'Искусственный интеллек – автор?',
		faq_text_4:
			'Согласно закону об авторском праве Республики Беларусь, авторское право на сгенерированные нейросетью изображения принадлежит автору ключевых слов, подобранных для создания изображения. Так как данные слова являются продуктом творческой деятельности человека.',
		faq_que_5: 'Для кого?',
		faq_text_5:
			'Любой желающий может приобрести один из шести или сразу все портреты университетов Беларуси. Это уникальные в своем роде иллюстрации, созданные искусственным интеллектом.',
		faq_que_6: 'Практическая значимость?',
		faq_text_6:
			'Коллекция разработана с целью демонстрации применения в сфере искусства технологии NFT. Дипломная работа, коллекция, имиджевый сайт являются готовым и законченным примером применения технологии в сфере искусства.',
		faq_que_7: 'Как получить NFT?',
		faq_text_7: 'Токены можно приобрести на торговой площадку для невзаимозаменяемых токенов – OpenSea.',
		//diploma
		diploma_title: 'Диплом',
		diploma_text:
			'Дипломный проект разработал студент 408 группы Качура Ярослав. Объектом дипломной работы является технология NFT. Предметом дипломной работы является технология NFT в дизайн-проекте цифрового искусства. Цель дипломной работы – теоретическое обоснование дизайн-проекта на основе технологии NFT в сфере цифрового искусства. Вся коллекция разработана искусственным интеллектом MidJourney и размещена на блокчейне Polygon. ',
		info_1: 'ВУЗОВ',
		info_2: 'СТРАНИЦ ДИПЛОМА',
		info_3: 'ГОДА ОБУЧЕНИЯ',
		info_4: 'СТРОК КОДА',
		info_5: 'ОПЫТА',
		//footer
		footer_text: 'Дипломный проект «Портреты университетов Беларуси»'
	}
}

$(function () {
	$('.translate').click(function () {
		var lang = $(this).attr('id')

		$('.lang').each(function (index, item) {
			$(this).text(arrLang[lang][$(this).attr('key')])
		})
	})
})

let translate = document.querySelectorAll('.translate') // Возвращает список элементов
let lastClicked = translate[0] // Первый элемент из списка (счет начинается с нуля)

for (let i = 0; i < translate.length; i++) {
	// Цикл берет и кругами выполняет код. На каждом круге, i является конкретным числом.
	// Добавляется событие 'клик' на test[0], потом test[1], test[2]...
	translate[i].addEventListener('click', function () {
		lastClicked.classList.remove('translate--active')
		this.classList.add('translate--active')
		// Убрали класс с предыдущего кликнутого элемента, добавили на текущий
		lastClicked = this
		// Обновили значение переменной - теперь она ссылается на текущий элемент.
		// Чтобы на следующем клике, убрать класс уже с этого.
	})
}

//slider

$('.gallery__slider').slick({
	dots: true,
	arrows: false,
	speed: 300,
	slidesToShow: 3,
	slidesToScroll: 3,
	responsive: [
		{
			breakpoint: 1024,
			settings: {
				slidesToShow: 3,
				slidesToScroll: 3,
				infinite: true,
				dots: true,
				arrows: false
			}
		},
		{
			breakpoint: 810,
			settings: {
				slidesToShow: 2,
				slidesToScroll: 2,
				arrows: false
			}
		},
		{
			breakpoint: 480,
			settings: {
				slidesToShow: 1,
				slidesToScroll: 1,
				arrows: false
			}
		}
	]
})

//header-bg

$(window).scroll(function (e) {
	var height = $(this).scrollTop()
	$('.header')[height >= 570 ? 'addClass' : 'removeClass']('header-nav--active')
})

//header-scroll

$("a[rel='m_PageScroll2id']").mPageScroll2id({
	scrollEasing: 'easeOutQuint',
	scrollSpeed: 900
})
